stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps: 
    - src/data/data_ingestion.py
    outs:
    - data/cleaned_data
  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
    - data/cleaned_data
    - src/features/feature_engineering.py
    outs:
    - data/Featured_data
  statistical_features:
    cmd: python3 src/features/statistical_features.py
    deps:
    - data/Featured_data
    - src/features/statistical_features.py
    params: 
    - statistical_features.correlation_threshold
    outs:
    - data/Final
  data_splitting:
    cmd: python3 src/data/data_splitting.py
    params: 
    - data_splitting.test_size
    deps:
    - data/Final
    - src/data/data_splitting.py
    outs:
    - data/Split_Data/train
    - data/Split_Data/test
  model_training:
    cmd: python3 src/model/model_training.py
    params:
    - model_training.max_depth
    - model_training.min_samples_split
    deps:
    - src/model/model_training.py
    - data/Split_Data/train
    - data/Split_Data/test
    outs:
    - Metrics